// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RealSolutionFolders
{
    internal sealed partial class Vsix
    {
        public const string Id = "Ch0pstix.VSExtensions.RealSolutionFolders2022";
        public const string Name = "Real Solution Folders (VS2022)";
        public const string Description = @"Adds an additional option under the 'Add' context menu for solutions in Visual Studio, allowing the creation of solution folders with actual directories (rather than just being used as visual organization items).";
        public const string Language = "en-US";
        public const string Version = "1.0.2";
        public const string Author = "Isaac Bickel (Ch0pstix)";
        public const string Tags = "";
    }
}
