// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RealSolutionFolders
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RealSolutionFoldersString = "ab742d1f-8ec5-469a-81f2-a61d1c2666c7";
        public static Guid RealSolutionFolders = new Guid(RealSolutionFoldersString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NewFolderCommand = 0x0100;
    }
}